name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.5
        bundler-cache: true
        working-directory: backend
    
    - name: Run RuboCop
      run: |
        cd backend
        bundle exec rubocop --parallel
    
    - name: Run Brakeman security scan
      run: |
        cd backend
        bundle exec brakeman --no-pager --format json --output brakeman-report.json || true
        bundle exec brakeman --no-pager

  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: rails_app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rails_app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://rails_app:password@localhost:5432/rails_app_test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.5
        bundler-cache: true
        working-directory: backend
    
    - name: Setup database
      run: |
        cd backend
        bundle exec rails db:create
        bundle exec rails db:migrate
    
    - name: Run tests
      run: |
        cd backend
        bundle exec rspec --exclude-pattern="spec/system/*"
    
    - name: Run system tests
      run: |
        cd backend
        bundle exec rspec spec/system/